config/routes.rb
Rails.application.routes.draw do
  resources :authors, except: [:destroy]
  resources :books, except: [:destroy]
  resources :accounts, except: [:destroy]

  delete '/accounts/:id/delete' => 'accounts#destroy', as: 'accounts_delete'
  get '/accounts/:id/delete' => 'accounts#destroy'

  delete '/authors/:id/delete' => 'authors#destroy', as: 'authors_delete'
  get '/authors/:id/delete' => 'authors#destroy'

  delete '/books/:id/delete' => 'books#destroy', as: 'books_delete'
  get '/books/:id/delete' => 'books#destroy'

  root 'authors#index' # Define a página inicial
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_FORMAT = /[^\s]@[^\s]/
  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: EMAIL_FORMAT }, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to authors_path, notice: 'Autor criado com sucesso.'
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)

    redirect_to root_path
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    params[:id] = nil
    flash[:notice] = "Author has been deleted"
    redirect_to :action => :index
  end

  private

  def set_author
    author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: 'Livro criado com sucesso.'
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: 'Livro atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    params[:id] = nil
    flash[:notice] = "Book has been deleted"
    redirect_to books_path, notice: 'Livro excluído com sucesso.'
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      reset_session
      session[:user_id] = user.id
      redirect_to root_path, notice: "olá " + user.email
    else
      redirect_to auth_login_path, alert: "Há algo de errado com suas credenciais, por favor verifique seus dados!"
    end
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/authors/edit.html.erb
<h1>Editar Autor</h1>

<%= form_with(model: @author, local: true) do |form| %>
  <div class="field">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Atualizar' %>
  </div>
<% end %>

<%= link_to 'Voltar', authors_path %>

app/views/authors/index.html.erb
<h1>Lista de Autores</h1>
<ul>
  <% @authors.each do |author| %>
    <li>
      <%= link_to author.name, author %>
    </li>
  <% end %>
</ul>

<%= link_to 'Novo Autor', new_author_path %>

app/views/authors/new.html.erb
<h1>Novo Autor</h1>

<%= form_with(model: @author, local: true) do |form| %>
  <div class="field">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar' %>
  </div>
<% end %>

<%= link_to 'Voltar', authors_path %>

app/views/authors/show.html.erb
<h1>Detalhes do Autor</h1>
<p><strong>Nome:</strong> <%= @author.name %></p>

<h2>Livros deste Autor</h2>
<ul>
  <% @author.books.each do |book| %>
    <li><%= link_to book.author_id, book %></li>
  <% end %>
</ul>

<%= link_to 'Editar', edit_author_path(@author) %> |
<%= button_to 'Delete',
            author_path(@author.id),
            method: :delete,
            data: { confirm: 'Are you sure?'} %> |
<%= link_to 'Voltar', authors_path %>

<hr>
<%= link_to 'Excluir 1', authors_delete_path(@author), method: :delete%>
<%= link_to 'Excluir 2', authors_delete_url(@author), method: :delete%>

app/views/books/edit.html.erb
<h1>Atualização de vinculamento de livros a autores</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <div class="field">
    <label>Título</label>
    <input type="text" name="titulo" placeholder="titulo" />
  </div>
  <div class="field">
    <%= form.label :author_id, 'Autor' %>
    <%= form.collection_select :author_id, Author.all, :id, :name, prompt: 'Selecione um autor' %>
  </div>
  <div class="actions">
    <%= form.submit 'Atualizar' %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>Lista de Livros</h1>
<ul>
  <% @books.each do |book| %>
  <li> <%= link_to book.author.name, book %></li>
  <% end %>
</ul>

<%= link_to "Novo", new_book_path%>

app/views/books/new.html.erb
<h1>Vincular livro ao autor</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <div class="field">
    <label>Título</label>
    <input type="text" name="titulo" placeholder="titulo" />
  </div>
  <div class="field">
    <%= form.label :author_id, 'Autor' %>
    <%= form.collection_select :author_id, Author.all, :id, :name, prompt: 'Selecione um autor' %>
  </div>
  <div class="actions">
    <%= form.submit 'Salvar' %>
  </div>
<% end %>

app/views/books/show.html.erb
<h1>Detalhes do Livro</h1>

<p><%= @book.author_id %></p>
<p><%= @book.id %></p>
<p><%= @book.author.name %></p>

<h1>Ações</h1>
<hr>
<%= link_to 'Editar', edit_book_path(@book) %>
<%= link_to 'Excluir 1', books_delete_path(@book), method: :delete%>
<%= link_to 'Excluir 2', books_delete_url(@book), method: :delete%>
<%= link_to 'Voltar', books_path %>

app/views/home/show.html.erb
<%= flash.notice %>


<h2>
    ola mundo
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>